### ISSUE TITLE
Sub-delegation limits

### ISSUE THREAD

**Issue by pegahcarter** [voteagora/liquid-delegator#2]
Have you given any thought into a subdelegate being able to further delegate their voting power to another address?  Here's an example:
- Some DEX has pair ABC/XYZ with the typical user LP model (user deposits ABC and XYZ into pair contract, receives LP token)
- The LP pair contract subdelegates the ABC and XYZ voting power back to the LP
- The LP wants to delegate their subdelegated voting power of ABC and XYZ to the protocol founders or some party who will actively vote

**Comment by pegahcarter** [comment]
Okay, I see how this can work now given the example:
```
Alligator.castVotesWithReasonBatched([[0xAAA, 0xBBB, 0xCCC], [0xFFF, 0xCCC]], 1, 1, "");
```
Question I have now - have considered gas challenges in casting votes with multiple sub-delegate paths?  It appears that you would need to pass in an array for each path of sub-delegation.

**Comment by jjranalli** [comment]
Closing as gas concerns for batch operations have been addressed in [AlligatorV2](https://github.com/voteagora/liquid-delegator/blob/main/src/v2/AlligatorV2.sol)
