### ISSUE TITLE
Alligator gives gas refunds but does not receive gas refunds

### ISSUE THREAD

**Issue by zobront** [voteagora/liquid-delegator#7]
## Summary

The `AlligatorV2.sol` contract has a function `castRefundableVotesWithReasonBatched()` which tracks the gas used and provides a refund to the user. This mirrors the functionality used by `NounsLogicV2` to provide voting refunds.

However, while Alligator can provide refunds, there's no way for it to be refunded by the underlying DAO. This is because Nouns (for example) requires a call to `castRefundableVote()` in order to provide a refund, but Alligator simply calls `castVotesWithReasonBatched()` which calls `Nouns.castVoteWithReason()`:

```solidity
function castRefundableVotesWithReasonBatched(
    Rules[] calldata proxyRules,
    address[][] calldata authorities,
    uint256 proposalId,
    uint8 support,
    string calldata reason
) external whenNotPaused {
    uint256 startGas = gasleft();
    castVotesWithReasonBatched(proxyRules, authorities, proposalId, support, reason);
    _refundGas(startGas);
}
```

```solidity
function castVotesWithReasonBatched(
    Rules[] calldata proxyRules,
    address[][] calldata authorities,
    uint256 proposalId,
    uint8 support,
    string calldata reason
) public whenNotPaused {
    address[] memory proxies = new address[](authorities.length);
    address[] memory authority;
    Rules memory rules;

    for (uint256 i; i < authorities.length; ) {
        authority = authorities[i];
        rules = proxyRules[i];
        validate(rules, msg.sender, authority, PERMISSION_VOTE, proposalId, support);
        proxies[i] = proxyAddress(authority[0], rules);
        INounsDAOV2(proxies[i]).castVoteWithReason(proposalId, support, reason);

        unchecked {
            ++i;
        }
    }

    emit VotesCast(proxies, msg.sender, authorities, proposalId, support);
}
```
The result is that Alligator will only refund users out of its own balance, but will not be refunded by the DAO. 

## Recommendation

Refactor `castRefundableVotesWithReasonBatched()` to use the `castRefundableVote()` entry point to the `governor` contract, so that it receives a refund before passing along the refund to the user.

**Comment by jjranalli** [comment]
Nice catch! Would add that – differently than NounsV2 governor – Alligator triggers refunds also when no votes are cast. I can think of two possible solutions:
- Trigger refunds only if governor has refunded Alligator
```solidity
// castRefundableVotesBatched

uint256 startBalance = address(this).balance;

for (uint256 i; i < authorities.length; ++i;) {
    // ...
    INounsDAOV2(proxies[i]).castRefundableVote(proposalId, support);
}

// Send refunds to sender if votes were cast successfully and governor has provided refunds.
if (address(this).balance > startBalance) {
    _refundGas(startGas);
}
```
- Assume that only governor can refill Alligator's balance (maybe add a safety check in `receive`), and thus get rid of the duplicated `_refundGas` logic and transfer the whole balance to sender each time.

**Comment by zobront** [comment]
Yep, that's great. Seems like Nouns doesn't need you to do anything except call the right function. I guess this makes sense since `tx.origin` is who is paying the gas. Good catch.

Do you want to try to build this to be general purpose across governor's that might use `msg.sender` instead, or is the idea to just make it right for Nouns and then customize it per project?

If you want to make it general purpose, I think the cleanest solution is to assume that Alligator should be holding no funds, and then simply check if `address(this).balance > 0` after casting the refundable vote and, if so, sending the full balance to the caller. 

But I also think it's reasonable to implement without that extra step and assume that calling the `castRefundableVoteWithReason()` function handles it.

**Comment by jjranalli** [comment]
> Do you want to try to build this to be general purpose across governor's that might use msg.sender instead, or is the idea to just make it right for Nouns and then customize it per project?

Yes, V2 is actually designed to be used also with other governors.

> If you want to make it general purpose, I think the cleanest solution is to assume that Alligator should be holding no funds, and then simply check if address(this).balance > 0 after casting the refundable vote and, if so, sending the full balance to the caller.

I've been thinking the same as well. Given the minimal impact on gas, I think it makes sense to add it as a generalized solution also to minimise the risk of funds getting locked in Alligator (for example due to governor upgrades).

**Comment by zobront** [comment]
@jjranalli Very elegant, I like it a lot.

I'm trying to think through to ensure there are no other situations where either:
- the refund payment is sent by an address besides the governor
- a payment is sent by governor that isn't a refund, and is sent to tx.origin when it doesn't make sense

I think we're safe from both of those situations. 
- For the first, I don't think that's a design that I've seen, and it Alligator would need to be adapted for that situation (but wouldn't come by surprise). 
- For the second, the only payments ever sent from the governor are gas refunds or withdrawals to the admin address. Assuming an Alligator Proxy should never be the governor's admin address, there isn't a risk for this.

The only other implication of this I can think of is that you'll want to remove `receive() external payable {}` from Alligator, but looks like that's already handled in the commit above, so that solution seems spot on.

**Comment by jjranalli** [comment]
@zobront I can't think of anything else and I share your thoughts on the two scenarios. We should be good 👍
